

###recuperar links
GET  http://localhost:3000/client/get
###
###recuperar links
GET  http://localhost:3000/sale/get
###

POST  http://localhost:1234/register
Content-Type: application/json

{
  "username": "john_doe",
  "email": "john.doe@example.com",
  "password": "securePassword1"
}
####
POST  http://localhost:1234/login
Content-Type: application/json

{
  "username": "john_doe",
  "password": "securePassword1"
}